- name: Run Proxy
  community.docker.docker_container:
    name: proxy_container
    image: martin16006/tp-devops-httpd
    networks: 
      - name: my_network
    ports:
      - "80:80"
      - "443:443"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
