- name: Launch App Container
  community.docker.docker_container:
    name: app_container
    image: myapp:latest
    env:
      APP_ENV: production
      DATABASE_URL: postgres://dbuser:dbpassword@db_container:5432/mydatabase
    networks:
      - name: my_app_network
