- name: Launch App Container
  community.docker.docker_container:
    name: app_container
    image: martin16006/tp-devops-simple-api
    networks:
      - name: my_network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
