- name: Launch Database Container
  community.docker.docker_container:
    name: db_container
    image: postgres:latest
    env:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: mydatabase
    networks:
      - name: my_app_network
