- name: Launch Database Container
  community.docker.docker_container:
    name: my-db
    image: martin16006/tp-devops-database
    networks:
      - name: my_network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
